### ISSUE TITLE
differentiate between two versions of Daisy resummation

### ISSUE THREAD

**Issue by suraj083** [suraj083/ewpt-model#9]
Create two types of field classes, field_daisy, field_nodaisy. The first will be like the current field class, the second one will have only h-dependent squared masses and a separate function for $\Pi(h, T)$ for each field.

Add a flag for daisy in the constructor of model class and if-else clause to test it.

Also, be aware of the change in the field class

**Comment by Upalaparna** [comment]
Consider adding different model classes in the model module and two variations of field classes in the field module.

**Comment by suraj083** [comment]
I have created a new branch called eft_nodaisy, where the effect of the resummation is captured through an overall term proportional to $\frac{T}{12\pi}$ in the effective potential.

The model definition in this branch will not contain boolean flags for eft or bsm.

The fields module now contains two different classes for thermally resummed masses and non-resummed masses.

The model.py module is currently under modification.

**Comment by suraj083** [comment]
I have added the $\cfrac{T}{12 \pi}$ term to the total potential and suitably separated the thermal and non-thermal masses.
